### ISSUE TITLE
PS3 Version Please :O

### ISSUE THREAD

**Issue by Bommel24** [LiEnby/GayMaker#1]
Hi,

I am a huge fan and I'd like to see a PS3 Version.
It seems possible ex.: https://www.reddit.com/r/ps3homebrew/comments/c4h8dn/worlds_first_gamemaker_studio_game_on_ps3/
However I can't launch it on my CFW because it always quits the game (saying data is corrupted). Can you please look into it?

Thank you :)

**Comment by KuromeSan** [comment]
maybe if i have spear time

**Comment by CelesteBlue-dev** [comment]
Please

**Comment by EGAMatsu** [comment]
> maybe if i have spear time

Please do it, i want to make ps3 games
